# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29031ba1efb2a8b73e461de290b13edff87acf9800f5b84977de27a6a8a3ff8ce91352c47fcaa9d31b62065b1285e8722b012fe06c881111f14aaae2b914c602

test:
  secret_key_base: 741a242107a01398c7cc21aabb250fb14e02bf11df06f12cc3a10f1e4b2b7516f8074f269af704245697ff5267a3a862fcf893dd4aed440a9a3a98dfb4b69ec7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
